apiVersion: aksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  resource-group: defaultRGroup
  location: eastus
  node-count: 2

nodePools:
  name: mynodepool
  resource-group: defaultRGroup
  cluster-name: cluster
  node-count: 1
  location: eastus
managedDisk:
  name: managedDIsk
  resource-group: defaultRGroup
  location: eastus
vnet:
  name: vnetDefault
