apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: defaultCluster
  resource-group: defaultRGroup
  location: eastus
  node-count: 2

nodePools:
    name: nodePool
    resource-group: defaultRGroup
    location: eastus
managedDisk:
    name: managedDisk
    resource-group: defaultRGroup
    location: eastus